[project]
name = "antastorga-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "jinja2>=3.1.6",
    "pdfkit>=1.0.0",
    "selenium>=4.35.0",
    "webdriver-manager>=4.0.2",
]
