name: Each week
on:
  workflow_dispatch:
  schedule:
    - cron: '30 11 * * SAT'
jobs:
  each_week:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 
          brew install pango
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install
      - name: Run make
        run: |
          make nextweek
      - name: commit docs
        run: |
          DATE_STR=`date "+%Y-%m-%d"`
          mkdir -p main/$DATE_STR
          cp -R build main/$DATE_STR
          git add .
          git stash save
          git checkout gh-pages
          rm -rf build
          git stash pop
          cd main

          echo '<!doctype html><html><head><title>Web Scrappers Results</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><link rel=\"stylesheet\" media=\"all\" href=\"https://theforeman.org/static/css/bootstrap.min.css\" /><link rel=\"stylesheet\" media=\"all\" href=\"https://theforeman.org/static/css/bootstrap-responsive.min.css\" /><link rel=\"stylesheet\" media=\"all\" href=\"https://theforeman.org/static/css/style.css\" /><link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\"></head><body style=\"margin:15px 15px\"><div class=\"list-group\">' | tr -d '\'  > index.html
          for i in **/D*.pdf; do
            k=`echo $i| cut -c  12-`
            echo '<a href="'"$i"'" class="list-group-item list-group-item-danger">'$k'</a><br>' >> index.html
          done
          echo "<hr>" >> index.html
          for i in **/D*.html; do
            k=`echo $i| cut -c  12-`
            echo '<a href="'"$i"'" class="list-group-item list-group-item-warning">'$k'</a><br>' >> index.html
          done
          echo "</div></body></html>" >> index.html

          cd -
          git add .
          git commit -m "update docs for main" || true
          git push origin gh-pages
