name: Each day
on:
  push:
    branches: [ develop ]
  pull_request:
  schedule:
    - cron: '0 6 * * *'
jobs:
  each_day:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install
      - name: Run make
        run: |
          make today
      - name: commit docs
        run: |
          git checkout gh-pages
          mkdir main
          mv build main
          echo "
            <!doctype html>
            <html>
              <head>
              <title>WebScrapper</title>
              <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
              <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
              </head>

              <body style="margin:0px 15px">
                <h1>Web Scrapper</h1>

                <hr />

                <div class="row plugin-manual">
                  <div class="col-md-4 center"><a href="main/" class="btn-doc btn"><i class="fa fa-newspaper-o"></i><p>main</p></a></div>
                </div>

              </body>
            </html>" > index.html
          git add main index.html
          git commit -m "update docs for $(basename ${GITHUB_REF})" || true
      - name: push docs
        run: git push origin gh-pages

